<CustomTreeNode>:
  BoxLayout:
    orientation: 'vertical'
    Label:
      text: 'Nombre funcion'
    Label:
      text: 'Parametros'

  BoxLayout:
    BoxLayout:
      orientation: 'vertical'
      Button:
        text: 'yes'
      Button:
        text: 'no'

    BoxLayout:
      orientation: 'vertical'
      Button:
        text: "trust"
      Button:
        text: "unacceptable"
      Button:
        text: "don't know"

  Label:
    text: 'estado'
