<CustomTreeNode>:
  # BoxLayout:
  #   orientation: 'vertical'
  #   Label:
  #     id: labelName
  #     text: 'Nombre funcion'
  #   Label:
  #     id: labelParams
  #     text: 'Parametros'
  #
  # BoxLayout:
  #   BoxLayout:
  #     orientation: 'vertical'
  #     Button:
  #       id: buttonYes
  #       text: 'yes'
  #     Button:
  #       id: buttonNo
  #       text: 'no'
  #
  #   BoxLayout:
  #     orientation: 'vertical'
  #     Button:
  #       id: buttonTrust
  #       text: "trust"
  #     Button:
  #       id: buttonUnacceptable
  #       text: "unacceptable"
  #     Button:
  #       id: buttonDontKnow
  #       text: "don't know"

  Label:
    id: labelState
    text: 'estado'
