<CustomTreeNode>:
  size: self.width, self.ids.labelName.height+self.ids.labelReturn.height
  BoxLayout:
    orientation: 'vertical'
    Label:
      size: self.texture_size[0], self.texture_size[1]
      text_size: self.width, None
      id: labelName
      text: 'Nombre funcion'
    Label:
      size: self.texture_size[0], self.texture_size[1]
      haling: 'left'
      text_size: self.width, None
      id: labelReturn
      text: 'Valor retornado: '

  BoxLayout:
    BoxLayout:
      orientation: 'vertical'
      Button:
        id: buttonYes
        text: 'V\u00e1lido'
        disabled: True
      Button:
        id: buttonNo
        text: 'Error'
        disabled: True

    BoxLayout:
      orientation: 'vertical'
      Button:
        id: buttonTrust
        text: "Confiar"
        disabled: True
      Button:
        id: buttonUnacceptable
        text: "Inaceptable"
        disabled: True
      Button:
        id: buttonDontKnow
        text: "Desconocido"
        disabled: True

  Label:
    id: labelState
    text: 'estado'


<Menu>:
  canvas:
    Color:
      rgb: 0.4,0.4,0.4
    Rectangle:
      size: self.size
      pos: self.pos
  size_hint: 1,0.2
  GridLayout:
    size_hint: .25,1
    rows: 2
    cols: 1
    AnchorLayout:
      anchor_x: 'right'
      anchor_y: 'bottom'
      GridLayout:
        size_hint: .9,.75
        cols: 2
        AnchorLayout:
          anchor_x: 'left'
          anchor_y: 'top'
          Button:
            size_hint: .98,.95
            id: buttonGo
            text: 'Debug'
        AnchorLayout:
          anchor_x: 'right'
          anchor_y: 'top'
          Button:
            size_hint: .98,.95
            id: buttonExit
            text: 'Salir'
    AnchorLayout:
      anchor_x: 'right'
      anchor_y: 'top'
      Spinner:
        id: spinnerEstrategia
        size_hint: .9,.75

  BoxLayout:
    Label:
      id: labelBuggyFunction
      text: 'La funcion buggy es: '
      color: 1,1,1,1


<DKPopup>:
  cols:1
  Label:
    id: labelInfoDK
  GridLayout:
    cols: 2
    size_hint_y: None
    height: '44sp'
    Button:
      id: buttonAccept
      text: 'Aceptar'
    Button:
      id: buttonCancel
      text: 'Cancelar'
